-- drop table if exists Photo;
-- drop table if exists book;
-- drop table if exists comment;
drop table if exists user_roles;
drop table if exists users;

create table if not exists book (
    id bigint generated by default as identity,
    body varchar(255),
    name varchar(255),
    subject varchar(255),
    create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    primary key (id)
);
CREATE TABLE IF NOT EXISTS comment (
    id uuid default random_uuid() not null,
    book_id bigint NOT NULL ,
    name varchar(255),
    body varchar(255),
    create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (id),
    foreign key (book_id) references book
);
create table if not exists Photo (
    id uuid default random_uuid() not null,
    content blob,
    content_type varchar(255),
    filename varchar(255),
    book_id bigint,
    create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    primary key (id), foreign key (book_id) references book
);
CREATE TABLE  if not exists users (
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (username)
);
CREATE TABLE IF NOT EXISTS user_roles (
    user_role_id INTEGER GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (user_role_id),
    FOREIGN KEY (username) REFERENCES users(username)
);

